#pragma once

#define PROJECT_NAME "alcubierre"
#define PROJECT_VER_TYPE "IDB"
#define PROJECT_VER  "0.1.0.0"
#define PROJECT_NAME_READABLE "Alcubierre"
#define PROJECT_BUILD_DATE "2020-02-26"
#define PROJECT_OS "Linux"

#define ALCUBIERRE_TYPE ""
#define ALCUBIERRE_OS ""
#define ALCUBIERRE_VERSION ""
#define ALCUBIERRE_NAME_HUMAN ""

#define ALCUBIERRE_BUILD_DATE ""
#define ALCUBIERRE_BUILD_CMAKE_VERSION "3.12.1"
#define ALCUBIERRE_BUILD_CMAKE_GENERATOR "Unix Makefiles"
#define ALCUBIERRE_BUILD_TOOLCHAIN ""
#define ALCUBIERRE_BUILD_C_FLAGS ""
#define ALCUBIERRE_BUILD_CXX_FLAGS ""
