#pragma once

#define PROJECT_NAME "alcubierre"
#define PROJECT_VER_TYPE "IDB"
#define PROJECT_VER  "0.1.0.0"
#define PROJECT_NAME_READABLE "Alcubierre"
#define PROJECT_BUILD_DATE "2021-08-29"
#define PROJECT_OS "Windows"
#define PROJECT_BUILD_TYPE "Debug"

#define ALCUBIERRE_TYPE ""
#define ALCUBIERRE_OS ""
#define ALCUBIERRE_VERSION ""
#define ALCUBIERRE_NAME_HUMAN ""

#define ALCUBIERRE_BUILD_DATE ""
#define ALCUBIERRE_BUILD_CMAKE_VERSION "3.20.21032501-MSVC_2"
#define ALCUBIERRE_BUILD_CMAKE_GENERATOR "Ninja"
#define ALCUBIERRE_BUILD_TOOLCHAIN ""
#define ALCUBIERRE_BUILD_C_FLAGS "/DWIN32 /D_WINDOWS /W3"
#define ALCUBIERRE_BUILD_CXX_FLAGS "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
